name: Build Windows x64 Release

on:
  push:
    branches:
      - test-gcc-action

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Build Release
        run: |
          make release_win64
      - name: Upload Release to github
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/Release/Win64/GoOfLife.exe
          asset_name: Windows x64 Release
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
