name: Build Windows x64 Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Test gcc
        run: |
          gcc --version
