name: Build Windows x64 Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Build Release
        run: |
          make release_win64
      - name: Create Release
        run: gh release create v0.0.1 -t "v0.0.1" ./build/release_win64/gh-action-test.exe
