name: Build Release Matrix

permissions:
  contents: write

on:
  push:
    branches:
      - test-matrix

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install X11 on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev
      - name: Install XQuartz on macOS
        if: matrix.os == 'macos-latest'
        run: brew install xquartz --cask
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Build Release
        run: |
          make $MAKE_VERSION release_win64
        env:
          MAKE_VERSION: github_actions_${{ matrix.os }}
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: GoOfLife-${{github.ref_name}}
          path: ./build/Release/**/*
          retention-days: 5

  # create-release:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download Releases
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: GoOfLife-${{github.ref_name}}
  #         path: ./download
  #     - name: Display Contents
  #       run: |
  #         ls -R ./download
