name: Build Release

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Build Release
        run: |
          make $MAKE_VERSION release_win64
        env:
          MAKE_VERSION: ${{ matrix.os }}
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: GoOfLife-${{github.ref_name}}
          path: ./build/Release/**/*

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Releases
        uses: actions/download-artifact@v2
        with:
          name: GoOfLife-${{github.ref_name}}
          path: ./download
      - name: Display Contents
        run: |
          ls -R ./download
