name: Build Windows x64 Release

on:
  push:
    branches:
      - test-gcc-action

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Test go
        run: |
          go -v
