name: Matrix Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build ${{ matrix.os }} AMD64
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install X11 on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev
      - name: Setup MinGW on Windows
        if: matrix.os == 'windows-latest'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Build Release
        run: |
          make $MAKE_VERSION
        env:
          MAKE_VERSION: github_actions_${{ matrix.os }}
