name: Build Windows x64 Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Build Release
        run: |
          make release_win64
      - name: Create Release
        run: gh release create $RELEASE_NAME -t "$RELEASE_NAME" ./build/Release/Win64/GoOfLife.exe
        env:
          RELEASE_NAME: ${{github.ref_name}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
