name: Build Windows x64 Release

on:
  push:
    branches:
      - test-gcc-action

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Build Release
        run: |
          go build ./cmd/main/main.go
      - name: Test run
        run: |
          ./main.exe
