name: Matrix Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86, x64]
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install X11 on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Build Release
        run: |
          make $MAKE_VERSION
        env:
          MAKE_VERSION: github_actions_${{ matrix.os }}
      - name: Upload Release
        uses: actions/upload-artifact@v3
        with:
          name: GoOfLife-${{github.ref_name}}
          path: ./build/*
          retention-days: 1

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    name: Add release to GitHub
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Releases
        uses: actions/download-artifact@v3
        with:
          name: GoOfLife-${{github.ref_name}}
          path: ./download
      - name: Create Release
        run: gh release create ${{github.ref_name}} ./download/*
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
