name: Export Win 64

on:
  workflow_dispatch:
  push:
    branches:
      - cache-mingw-in-workflows

jobs:
  build:
    name: Export Win64
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Enable MinGW cache on Windows
        run: |
          echo ("CACHE_MONTH=" + $(date '+%b %Y')) >> $env:GITHUB_ENV
      - name: Cache MinGW on Windows
        id: cache-mingw
        uses: actions/cache@v3
        with:
          path: C:\ProgramData\chocolatey\lib\mingw
          key: ${{ env.CACHE_MONTH }}
      - name: Setup MinGW on Windows
        if: steps.cache-mingw.outputs.cache-hit != 'true'
        uses: coffeebe4code/setup-mingw@v1-beta-2
        with:
          platform: x64
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Build Release
        run: |
          make $MAKE_VERSION
        env:
          MAKE_VERSION: release_win64
      - name: Upload Export
        uses: actions/upload-artifact@v3
        with:
          name: GoOfLife-Win64.exe
          path: ./build/*
          retention-days: 1
